#!/usr/bin/env python3
"""Bake a draped floor-seal sheet into cave_world_holed.obj (the collision mesh).

The vendored LTU SubT cave mesh has a genuinely sparse / gappy floor across the
drive corridor (it is a stylised cave with rubble, ramps and real holes, not a
watertight surface). This tool closes those gaps for physics by generating a
triangulated "seal" sheet draped a few centimetres UNDER the real mesh floor, so
the real rugged floor still carries the vehicle wherever it exists and the seal
only becomes the contact surface over an actual hole.

The sheet is appended to cave_world_holed.obj between `# >>> cavex_floor_seal >>>`
markers (one trimesh -> one collision BVH). model.sdf points <collision> at this
file and <visual> at the separate cave_world_visual.obj, so the seal is never
drawn. Run this AFTER trim_cave_mesh.py.

Idempotent: strips its own previous block and re-appends each run; retune the
parameters below freely. `git checkout cave_world_holed.obj` reverts.

World <-> mesh-local frame (model.sdf applies <scale>2 2 2</scale>, the world
<include> pose is `18.7830 31.4050 5.9826  1.5708 0 1.5708`)::

    world_x = 2*z_local + 18.7830      z_local = (world_x - 18.7830) / 2
    world_y = 2*x_local + 31.4050      x_local = (world_y - 31.4050) / 2
    world_z = 2*y_local +  5.9826      y_local = (world_z -  5.9826) / 2

i.e. local (x,y,z) -> world (z,x,y)*2 + t, so world +Z (up) == local +Y.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

MESH_DIR = Path(__file__).resolve().parent.parent
OBJ = MESH_DIR / "cave_world_holed.obj"          # sampled for the drape, cleaned of old seal blocks
SEAL_OBJ = MESH_DIR / "cave_floor_seal.obj"      # generated, collision-only

BEGIN = "# >>> cavex_floor_seal (generated by tools/add_floor_seal.py) >>>"
END = "# <<< cavex_floor_seal <<<"
GROUP = "cavex_floor_seal"

# --- seal footprint, WORLD frame ----------------------------------------------
# Rectangular panels (x0, x1, y0, y1). Each is draped onto the real mesh floor
# where one exists and filled flat (~FALLBACK_Z) over gaps. Panels overlap a few
# metres so there is no seam. The flooded-basin void (x in [BASIN_X0, BASIN_X1])
# is punched back out of any panel that crosses it, so the basin keeps its depth.
#
# These replace the box models cave_floor_patch / _scaled / _bridge that used to
# be in cavex_world.world: same footprints, now draped mesh instead of flat
# collision boxes at z=5.2. y runs ~1 m past each old box so edge sampling is
# covered; the overhang tucks under the cave walls.
BASIN_X0, BASIN_X1 = 0.0, 32.0
PANELS = [
    (-43.0,   0.0, -13.0, 13.0),   # water approach / dry corridor   (was cave_floor_patch,        x[-40,-1] y[-12,12])
    ( 32.0,  41.0, -13.0, 13.0),   # corridor east of the basin (mesh cut at x=40)
    (-122.0, -58.0, -48.0, -15.0), # spawn area at world (-88.78,-31.4) (was cave_floor_patch_scaled, x[-120,-60] y[-46,-17])
    (-64.0,  -36.0, -48.0, 14.0),  # spawn -> water-approach link      (was cave_floor_patch_bridge, x[-62,-38] y[-46,12])
]
GRID = 1.0  # metres between grid nodes

# --- drape parameters ----------------------------------------------------------
DROP = 0.05          # seal sits this far below the sampled real floor
FLOOR_BAND = (4.5, 9.0)  # world-z window that counts as "floor" (excludes ceiling)
# The real corridor floor is a near-flat plane at world z ~= 5.98 (measured);
# rare rubble/ramp spikes reach ~8 m. Clip samples into the floor cluster before
# draping so a rubble spike next to a hole does not pull the seal up with it.
SAMPLE_CLIP = (5.4, 6.1)
Z_CLAMP = (5.4, 6.2)     # sanity clamp on the final seal height
FALLBACK_Z = 5.90        # used only if a whole region has no floor to sample


def load_obj(path: Path):
    verts, faces = [], []
    lines = path.read_text().splitlines()
    for ln in lines:
        if ln.startswith("v "):
            _, x, y, z = ln.split()[:4]
            verts.append((float(x), float(y), float(z)))
        elif ln.startswith("f "):
            idx = [int(t.split("/")[0]) for t in ln.split()[1:]]
            for i in range(1, len(idx) - 1):
                faces.append((idx[0] - 1, idx[i] - 1, idx[i + 1] - 1))
    return lines, np.array(verts), np.array(faces, dtype=np.int64)


def to_world(v_local: np.ndarray) -> np.ndarray:
    wx = 2 * v_local[:, 2] + 18.7830
    wy = 2 * v_local[:, 0] + 31.4050
    wz = 2 * v_local[:, 1] + 5.9826
    return np.column_stack([wx, wy, wz])


def sample_floor(Wx, Wy, tri, pts):
    """Lowest triangle-surface world-z in FLOOR_BAND under each (x,y) in pts.

    Returns an array of z (NaN where nothing in the band covers the column).
    """
    a, b, c = tri[:, 0], tri[:, 1], tri[:, 2]
    # prefilter to corridor floor triangles
    zmin = np.minimum.reduce([a[:, 2], b[:, 2], c[:, 2]])
    zmax = np.maximum.reduce([a[:, 2], b[:, 2], c[:, 2]])
    ymin = np.minimum.reduce([a[:, 1], b[:, 1], c[:, 1]])
    ymax = np.maximum.reduce([a[:, 1], b[:, 1], c[:, 1]])
    xmin = np.minimum.reduce([a[:, 0], b[:, 0], c[:, 0]])
    xmax = np.maximum.reduce([a[:, 0], b[:, 0], c[:, 0]])
    gx0 = min(p[0] for p in PANELS)
    gx1 = max(p[1] for p in PANELS)
    gy0 = min(p[2] for p in PANELS)
    gy1 = max(p[3] for p in PANELS)
    keep = (
        (zmax >= FLOOR_BAND[0] - 1) & (zmin <= FLOOR_BAND[1] + 1)
        & (ymax >= gy0 - 3) & (ymin <= gy1 + 3)
        & (xmax >= gx0 - 3) & (xmin <= gx1 + 3)
    )
    a, b, c = a[keep], b[keep], c[keep]
    ax, ay = a[:, 0], a[:, 1]
    e0 = b[:, :2] - a[:, :2]
    e1 = c[:, :2] - a[:, :2]
    d00 = (e0 * e0).sum(1)
    d01 = (e0 * e1).sum(1)
    d11 = (e1 * e1).sum(1)
    den = d00 * d11 - d01 * d01
    ok = np.abs(den) > 1e-12
    tbx0 = np.minimum.reduce([a[:, 0], b[:, 0], c[:, 0]])
    tbx1 = np.maximum.reduce([a[:, 0], b[:, 0], c[:, 0]])
    tby0 = np.minimum.reduce([a[:, 1], b[:, 1], c[:, 1]])
    tby1 = np.maximum.reduce([a[:, 1], b[:, 1], c[:, 1]])

    out = np.full(len(pts), np.nan)
    for i, (px, py) in enumerate(pts):
        m = ok & (tbx0 <= px) & (tbx1 >= px) & (tby0 <= py) & (tby1 >= py)
        if not m.any():
            continue
        v2x = px - ax[m]
        v2y = py - ay[m]
        d20 = e0[m, 0] * v2x + e0[m, 1] * v2y
        d21 = e1[m, 0] * v2x + e1[m, 1] * v2y
        vv = (d11[m] * d20 - d01[m] * d21) / den[m]
        ww = (d00[m] * d21 - d01[m] * d20) / den[m]
        uu = 1 - vv - ww
        ins = (uu >= -1e-6) & (vv >= -1e-6) & (ww >= -1e-6)
        if not ins.any():
            continue
        z = uu[ins] * a[m][ins, 2] + vv[ins] * b[m][ins, 2] + ww[ins] * c[m][ins, 2]
        z = z[(z >= FLOOR_BAND[0]) & (z <= FLOOR_BAND[1])]
        if z.size:
            out[i] = z.min()
    return out


def fill_nans(grid: np.ndarray) -> np.ndarray:
    """Relax NaN cells to the mean of their non-NaN 4-neighbours, iteratively."""
    g = grid.copy()
    if np.isnan(g).all():
        return np.full_like(g, FALLBACK_Z)
    for _ in range(2000):
        nan = np.isnan(g)
        if not nan.any():
            break
        acc = np.zeros_like(g)
        cnt = np.zeros_like(g)
        for sy, sx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            sh = np.roll(g, (sy, sx), (0, 1))
            good = ~np.isnan(sh)
            acc[good] += sh[good]
            cnt[good] += 1
        upd = nan & (cnt > 0)
        g[upd] = acc[upd] / cnt[upd]
    g[np.isnan(g)] = FALLBACK_Z
    return g


def build_panel(x0, x1, y0, y1, floor_lookup):
    xs = np.arange(x0, x1 + 1e-6, GRID)
    ys = np.arange(y0, y1 + 1e-6, GRID)
    # clip a panel that borders the basin void so it does not re-cover it
    xs = xs[(xs <= BASIN_X0 + 1e-6) | (xs >= BASIN_X1 - 1e-6)]
    XX, YY = np.meshgrid(xs, ys)  # (ny, nx)
    pts = np.column_stack([XX.ravel(), YY.ravel()])
    z = floor_lookup(pts).reshape(XX.shape)
    with np.errstate(invalid="ignore"):
        z = np.where(np.isnan(z), z, np.clip(z, *SAMPLE_CLIP))
    z = fill_nans(z) - DROP
    z = np.clip(z, *Z_CLAMP)

    ny, nx = XX.shape
    # local-frame vertices: local (x,y,z) from world (X,Y,Zseal)
    lx = (YY - 31.4050) / 2.0
    ly = (z - 5.9826) / 2.0
    lz = (XX - 18.7830) / 2.0
    vloc = np.column_stack([lx.ravel(), ly.ravel(), lz.ravel()])

    quads = []
    for j in range(ny - 1):
        for i in range(nx - 1):
            a = j * nx + i
            b = j * nx + (i + 1)
            c = (j + 1) * nx + (i + 1)
            d = (j + 1) * nx + i
            quads.append((a, b, c, d))
    return vloc, quads


def _clean_holed_obj() -> bool:
    """Strip any leftover baked-in seal block from cave_world_holed.obj."""
    lines = OBJ.read_text().splitlines()
    kept, skip, found = [], False, False
    for ln in lines:
        if ln.startswith(BEGIN):
            skip, found = True, True
            continue
        if ln.startswith(END):
            skip = False
            continue
        if not skip:
            kept.append(ln)
    if found:
        OBJ.write_text("\n".join(kept) + "\n")
    return found


def main() -> int:
    _clean_holed_obj()  # drop any previous seal block, get a clean base
    if SEAL_OBJ.exists():
        SEAL_OBJ.unlink()  # retire the old standalone-file approach

    base_lines, verts, faces = load_obj(OBJ)
    tri_world = to_world(verts.reshape(-1, 3)).reshape(-1, 3)[faces]  # (F,3,3)
    base_v = sum(1 for ln in base_lines if ln.startswith("v "))
    base_vn = sum(1 for ln in base_lines if ln.startswith("vn "))

    def lookup(pts):
        return sample_floor(None, None, tri_world, pts)

    seal = [
        BEGIN,
        "# baked into this collision+visual mesh; the model's <visual> points at a",
        "# separate clean mesh so this is not drawn. Regenerate: tools/add_floor_seal.py",
        f"g {GROUP}",
    ]
    vlines, flines = [], []
    nrm = base_vn + 1
    vcount = base_v
    added_v = added_f = 0
    for (x0, x1, y0, y1) in PANELS:
        vloc, quads = build_panel(x0, x1, y0, y1, lookup)
        for (lx, ly, lz) in vloc:
            vlines.append(f"v {lx:.6f} {ly:.6f} {lz:.6f}")
        added_v += len(vloc)
        for (a, b, c, d) in quads:
            A, B, C, D = (vcount + a + 1, vcount + b + 1, vcount + c + 1, vcount + d + 1)
            flines.append(f"f {A}//{nrm} {B}//{nrm} {C}//{nrm}")
            flines.append(f"f {A}//{nrm} {C}//{nrm} {D}//{nrm}")
            added_f += 2
        vcount += len(vloc)
    seal += vlines + [f"vn 0.000000 1.000000 0.000000"] + flines + [END]

    OBJ.write_text("\n".join(base_lines + seal) + "\n")
    print(f"baked seal into {OBJ.name}: +{added_v} verts, +{added_f} tris")
    for p in PANELS:
        print(f"  panel world x[{p[0]},{p[1]}] y[{p[2]},{p[3]}]")
    print(f"  basin void x [{BASIN_X0},{BASIN_X1}] left open")
    return 0


if __name__ == "__main__":
    sys.exit(main())
