import React, { useEffect, useRef, useState } from "react";
import { RobotState, SensorData } from "../types";
import {
  Camera,
  Radio,
  Waves,
  Activity,
  Scan,
  ShieldAlert,
  Battery,
  BatteryCharging,
  BatteryWarning,
  Zap,
  AlertTriangle,
  RefreshCw,
  Video,
  Circle,
  Sun,
  Maximize2,
  Wifi,
  Rss,
  Server,
  Map,
  Box,
  Layers,
  Download,
  CheckCircle2,
  Compass,
  Eye,
  Share2,
  Grid,
  Sliders,
  Database,
  Sparkles,
} from "lucide-react";

interface SensorDashboardProps {
  robotState: RobotState;
  sensorData: SensorData;
  onSetBattery?: (val: number) => void;
  onToggleSonar?: () => void;
  onToggleWifi?: () => void;
}

export const SensorDashboard: React.FC<SensorDashboardProps> = ({
  robotState,
  sensorData,
  onSetBattery,
  onToggleSonar,
  onToggleWifi,
}) => {
  const lidarCanvasRef = useRef<HTMLCanvasElement>(null);
  const cameraCanvasRef = useRef<HTMLCanvasElement>(null);

  const isLowBattery = robotState.battery < 20;

  // Video Recording State
  const [isRecording, setIsRecording] = useState(false);
  const [recordSeconds, setRecordSeconds] = useState(0);

  // 3D SLAM Mapping Result Window Canvas & Controls
  const mapCanvasRef = useRef<HTMLCanvasElement>(null);
  const [mapViewMode, setMapViewMode] = useState<"iso" | "topdown" | "side">("iso");
  const [showLidarLayer, setShowLidarLayer] = useState(true);
  const [showSonarLayer, setShowSonarLayer] = useState(true);
  const [showWifiLayer, setShowWifiLayer] = useState(true);
  const [showWaypointsLayer, setShowWaypointsLayer] = useState(true);
  const [mapZoom, setMapZoom] = useState(1.0);
  const [isExportingMap, setIsExportingMap] = useState(false);

  // PCD Point Cloud Data Export Function
  const handleExportPcdMap = () => {
    setIsExportingMap(true);
    setTimeout(() => {
      let pcdContent = `# .PCD v.7 - Point Cloud Data file generated by CaveX 3D SLAM Engine\n`;
      pcdContent += `VERSION .7\nFIELDS x y z rgb\nSIZE 4 4 4 4\nTYPE F F F U\nCOUNT 1 1 1 1\n`;
      pcdContent += `WIDTH 142850\nHEIGHT 1\nVIEWPOINT 0 0 0 1 0 0 0\nPOINTS 142850\nDATA ascii\n`;

      // Generate synthetic point cloud records matching the 3 sections
      for (let i = 0; i < 200; i++) {
        const x = (-15 + Math.random() * 30).toFixed(3);
        const y = (-3 + Math.random() * 6).toFixed(3);
        const z = (Math.random() * 24.5).toFixed(3);
        const rgb = 16777215; // white
        pcdContent += `${x} ${y} ${z} ${rgb}\n`;
      }

      const blob = new Blob([pcdContent], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `cavex_3d_slam_pointcloud_map_${Date.now()}.pcd`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      setIsExportingMap(false);
    }, 600);
  };

  // FPV Brightness / Gain state
  const [brightnessLevel, setBrightnessLevel] = useState<"standard" | "high" | "ultra">("high");

  // Timer for video recording
  useEffect(() => {
    let interval: any = null;
    if (isRecording) {
      interval = setInterval(() => {
        setRecordSeconds((s) => s + 1);
      }, 1000);
    } else {
      setRecordSeconds(0);
    }
    return () => clearInterval(interval);
  }, [isRecording]);

  const formatRecordTime = (totalSec: number) => {
    const mins = Math.floor(totalSec / 60)
      .toString()
      .padStart(2, "0");
    const secs = (totalSec % 60).toString().padStart(2, "0");
    return `${mins}:${secs}`;
  };

  // Render Simulated Visual Camera with ORB SLAM Features (Enhanced Brightness)
  useEffect(() => {
    const canvas = cameraCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = canvas.width;
    const h = canvas.height;

    // Background cavern illumination based on position & mode (BRIGHTENED)
    const isWater = robotState.position.x >= -5 && robotState.position.x <= 12;
    const isAirPocket = robotState.position.x > 12;

    // Gain multipliers
    const gainFactor = brightnessLevel === "ultra" ? 1.8 : brightnessLevel === "high" ? 1.4 : 1.0;

    const grad = ctx.createLinearGradient(0, 0, 0, h);
    if (isWater && robotState.position.z < 0) {
      grad.addColorStop(0, brightnessLevel === "ultra" ? "#004080" : "#002b52");
      grad.addColorStop(1, brightnessLevel === "ultra" ? "#001a33" : "#001224");
    } else if (isAirPocket) {
      grad.addColorStop(0, brightnessLevel === "ultra" ? "#3b1e66" : "#28124a");
      grad.addColorStop(1, brightnessLevel === "ultra" ? "#1a0d33" : "#100724");
    } else {
      grad.addColorStop(0, brightnessLevel === "ultra" ? "#4a3c30" : "#33271f");
      grad.addColorStop(1, brightnessLevel === "ultra" ? "#241a14" : "#1a120d");
    }
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, w, h);

    // High Intensity Headlight / High-Gain Exposure Light
    const spotlightAlpha = Math.min(0.9, 0.55 * gainFactor);
    const lightGrad = ctx.createRadialGradient(w / 2, h / 2, 5, w / 2, h / 2, h * 0.9);
    lightGrad.addColorStop(0, `rgba(255, 245, 210, ${spotlightAlpha})`);
    lightGrad.addColorStop(0.5, `rgba(255, 215, 170, ${spotlightAlpha * 0.5})`);
    lightGrad.addColorStop(1, "rgba(255, 255, 255, 0.05)");
    ctx.fillStyle = lightGrad;
    ctx.fillRect(0, 0, w, h);

    // Draw cave horizon / tunnel walls (Brighter stroke)
    ctx.strokeStyle = `rgba(255, 255, 255, ${0.35 * gainFactor})`;
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(w / 2, h / 2, h * 0.38, 0, Math.PI * 2);
    ctx.stroke();

    // Secondary bright tunnel outline
    ctx.strokeStyle = `rgba(56, 189, 248, ${0.25 * gainFactor})`;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.arc(w / 2, h / 2, h * 0.2, 0, Math.PI * 2);
    ctx.stroke();

    // Draw ORB Feature Trackers (Vivid Lime points with ID tags)
    ctx.fillStyle = "#00ff88";
    ctx.font = "10px monospace";
    for (let i = 0; i < sensorData.featurePointsCount; i++) {
      const seed = i * 137.5;
      const fx = w / 2 + Math.cos(seed) * (h * 0.35 * Math.sin(seed * 0.1));
      const fy = h / 2 + Math.sin(seed) * (h * 0.35 * Math.sin(seed * 0.1));

      ctx.beginPath();
      ctx.arc(fx, fy, 3, 0, Math.PI * 2);
      ctx.fill();

      // Draw feature crosshair
      ctx.strokeStyle = "rgba(0, 255, 136, 0.8)";
      ctx.beginPath();
      ctx.moveTo(fx - 5, fy);
      ctx.lineTo(fx + 5, fy);
      ctx.moveTo(fx, fy - 5);
      ctx.lineTo(fx, fy + 5);
      ctx.stroke();
    }

    // Camera HUD Overlay Text
    ctx.fillStyle = "#38bdf8";
    ctx.font = "10px monospace";
    ctx.fillText(`CAM0: FRONT_RGB [${sensorData.cameraResolution}]`, 10, 18);
    ctx.fillText(`EXPOSURE: +${(gainFactor * 1.5).toFixed(1)} EV (${brightnessLevel.toUpperCase()})`, 10, 32);
    ctx.fillText(`ORB-SLAM3: ${sensorData.featurePointsCount} FEATS`, 10, 46);

    // Recording Badge on Canvas if active
    if (isRecording) {
      ctx.fillStyle = "#ef4444";
      ctx.beginPath();
      ctx.arc(w - 20, 20, 6, 0, Math.PI * 2);
      ctx.fill();

      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 11px monospace";
      ctx.fillText(`REC ${formatRecordTime(recordSeconds)}`, w - 90, 24);
    }
  }, [robotState, sensorData, brightnessLevel, isRecording, recordSeconds]);

  // Render 2D SLAM Occupancy Grid Map & LiDAR Scan Rays
  useEffect(() => {
    const canvas = lidarCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = canvas.width;
    const h = canvas.height;
    const cx = w / 2;
    const cy = h / 2;

    // Dark grid background
    ctx.fillStyle = "#090d16";
    ctx.fillRect(0, 0, w, h);

    // Grid lines
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 1;
    const gridSize = 20;
    for (let x = 0; x < w; x += gridSize) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, h);
      ctx.stroke();
    }
    for (let y = 0; y < h; y += gridSize) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(w, y);
      ctx.stroke();
    }

    // Radar distance rings
    ctx.strokeStyle = "rgba(56, 189, 248, 0.2)";
    [40, 80, 120].forEach((r) => {
      ctx.beginPath();
      ctx.arc(cx, cy, r, 0, Math.PI * 2);
      ctx.stroke();
    });

    // Render 2D LiDAR Range Readings (Cyan/Lime dots & laser beams)
    ctx.strokeStyle = "rgba(0, 255, 180, 0.15)";
    ctx.fillStyle = "#00ffb4";

    const ranges = sensorData.lidarRanges;
    const step = (Math.PI * 2) / ranges.length;

    ctx.beginPath();
    ranges.forEach((range, i) => {
      const angle = i * step;
      const scale = 16; // 1 meter = 16px
      const lx = cx + Math.cos(angle) * (range * scale);
      const ly = cy + Math.sin(angle) * (range * scale);

      ctx.moveTo(cx, cy);
      ctx.lineTo(lx, ly);

      // Point at hit location
      ctx.fillRect(lx - 1.5, ly - 1.5, 3, 3);
    });
    ctx.stroke();

    // Robot Position Marker in 2D SLAM Map
    ctx.fillStyle = "#f59e0b";
    ctx.beginPath();
    ctx.arc(cx, cy, 5, 0, Math.PI * 2);
    ctx.fill();

    // Robot Heading Direction Arrow
    const yawRad = (robotState.orientation.z * Math.PI) / 180;
    ctx.strokeStyle = "#f59e0b";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.lineTo(cx + Math.cos(yawRad) * 14, cy + Math.sin(yawRad) * 14);
    ctx.stroke();

    // Map Legend
    ctx.fillStyle = "#94a3b8";
    ctx.font = "10px monospace";
    ctx.fillText(`SLAM Toolbox 2D Grid (10m x 10m)`, 8, 16);
    ctx.fillText(`Confidence: ${sensorData.slamConfidence.toFixed(0)}%`, 8, 30);
  }, [sensorData, robotState]);

  // Render 3D SLAM Mapping Result Window Canvas
  useEffect(() => {
    const canvas = mapCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = canvas.width;
    const h = canvas.height;

    // Dark sleek map background
    ctx.fillStyle = "#030712";
    ctx.fillRect(0, 0, w, h);

    // Draw Grid Pattern
    ctx.strokeStyle = "#111827";
    ctx.lineWidth = 1;
    const gridSize = 24 * mapZoom;
    for (let x = 0; x < w; x += gridSize) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, h);
      ctx.stroke();
    }
    for (let y = 0; y < h; y += gridSize) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(w, y);
      ctx.stroke();
    }

    // Coordinate mapping helper from 3D ROS space (x: -18 to +22, y: -5 to +5, z: -3 to +25)
    // to 2D Canvas Screen coordinates based on selected mapViewMode
    const toScreen = (rx: number, ry: number, rz: number) => {
      if (mapViewMode === "topdown") {
        // 2D Top Down View (x along canvas width, y along canvas height)
        const sx = ((rx + 18) / 42) * w * mapZoom + (1 - mapZoom) * (w / 2);
        const sy = h / 2 + (ry / 10) * (h * 0.7) * mapZoom;
        return { x: sx, y: sy };
      } else if (mapViewMode === "side") {
        // Side Elevation Profile View (x along width, z altitude along height)
        const sx = ((rx + 18) / 42) * w * mapZoom + (1 - mapZoom) * (w / 2);
        const sy = h * 0.82 - (rz / 26) * (h * 0.75) * mapZoom;
        return { x: sx, y: sy };
      } else {
        // Isometric 3D Projection
        const isoX = (rx * 0.85 - ry * 0.85) * 11 * mapZoom;
        const isoY = (rx * 0.35 + ry * 0.35) * 8 * mapZoom - rz * 6 * mapZoom;
        const sx = w * 0.38 + isoX;
        const sy = h * 0.65 + isoY;
        return { x: sx, y: sy };
      }
    };

    // 1. Draw Section Boundaries & Cavern Enclosures
    ctx.strokeStyle = "rgba(75, 85, 99, 0.4)";
    ctx.lineWidth = 1;
    ctx.setLineDash([4, 4]);

    // Section 1: Dry Cave (-18 to -5)
    const sec1A = toScreen(-18, 0, 0);
    const sec1B = toScreen(-5, 0, 0);
    ctx.beginPath();
    ctx.moveTo(sec1A.x, sec1A.y);
    ctx.lineTo(sec1B.x, sec1B.y);
    ctx.stroke();

    // Section 2: Flooded Water (-5 to 12)
    const sec2A = toScreen(-5, 0, 0);
    const sec2B = toScreen(12, 0, 0);
    ctx.strokeStyle = "rgba(6, 182, 212, 0.5)";
    ctx.beginPath();
    ctx.moveTo(sec2A.x, sec2A.y);
    ctx.lineTo(sec2B.x, sec2B.y);
    ctx.stroke();

    // Section 3: Vertical Shaft (12 to 22, height up to 25m)
    const shaftBase = toScreen(18, 0, 0);
    const shaftApex = toScreen(18, 0, 24);
    ctx.strokeStyle = "rgba(168, 85, 247, 0.6)";
    ctx.beginPath();
    ctx.moveTo(shaftBase.x, shaftBase.y);
    ctx.lineTo(shaftApex.x, shaftApex.y);
    ctx.stroke();
    ctx.setLineDash([]);

    // 2. Render Point Cloud Layers
    // Layer 1: Dry Cave Rock Points (Amber/Orange)
    if (showLidarLayer) {
      ctx.fillStyle = "#f59e0b";
      for (let i = 0; i < 180; i++) {
        const seed = i * 1.618;
        const px = -15 + (i / 180) * 10;
        const py = Math.sin(seed * 3) * 1.8;
        const pz = 0.5 + Math.cos(seed * 2) * 1.2;
        const pt = toScreen(px, py, pz);
        ctx.fillRect(pt.x - 1, pt.y - 1, 2, 2);
      }
    }

    // Layer 2: Flooded Water Seabed Bathymetry Points (Cyan/Teal)
    if (showSonarLayer) {
      ctx.fillStyle = "#06b6d4";
      for (let i = 0; i < 220; i++) {
        const seed = i * 2.718;
        const px = -5 + (i / 220) * 17;
        const py = Math.cos(seed * 2) * 2.2;
        const pz = -0.5 - Math.sin(seed * 4) * 1.5; // underwater seabed depth profile
        const pt = toScreen(px, py, pz);
        ctx.fillRect(pt.x - 1, pt.y - 1, 2, 2);
      }
    }

    // Layer 3: Vertical Ascent Shaft Chimney Helical Point Cloud (Magenta/Sky-Blue)
    if (showLidarLayer) {
      for (let i = 0; i < 380; i++) {
        const angle = i * 0.25;
        const radius = 2.2 + Math.sin(i * 0.1) * 0.8;
        const px = 18.0 + Math.cos(angle) * radius;
        const py = Math.sin(angle) * radius;
        const pz = (i / 380) * 24.5; // ascending 25m shaft
        const pt = toScreen(px, py, pz);

        ctx.fillStyle = pz > 15 ? "#c084fc" : "#38bdf8";
        ctx.fillRect(pt.x - 1.2, pt.y - 1.2, 2.4, 2.4);
      }
    }

    // Layer 4: WiFi Video Stream SLAM Keyframe Markers (Lime/Yellow)
    if (showWifiLayer) {
      ctx.fillStyle = "#a3e635";
      for (let k = 0; k < 12; k++) {
        const kx = 12 + (k % 4) * 2;
        const ky = Math.sin(k) * 1.2;
        const kz = 2 + k * 1.8;
        const pt = toScreen(kx, ky, kz);

        ctx.beginPath();
        ctx.arc(pt.x, pt.y, 3, 0, Math.PI * 2);
        ctx.fill();
      }
    }

    // 3. Render Waypoint Trajectory Lines
    if (showWaypointsLayer) {
      const waypoints = [
        { x: -15, y: 0, z: 0.6 },
        { x: -10, y: -0.5, z: 0.6 },
        { x: -5, y: 0, z: 0.6 },
        { x: 0, y: -0.4, z: 0.55 },
        { x: 4, y: 0.3, z: 0.55 },
        { x: 8, y: 0, z: 0.55 },
        { x: 11, y: 0, z: 0.8 },
        { x: 13, y: 0, z: 2.0 },
        { x: 17.2, y: 1.5, z: 5.5 },
        { x: 18.8, y: -1.5, z: 8.5 },
        { x: 18.0, y: 0.8, z: 12.0 },
        { x: 18.8, y: -1.2, z: 15.5 },
        { x: 17.5, y: 1.2, z: 19.0 },
        { x: 18.5, y: 0, z: 23.5 },
      ];

      ctx.strokeStyle = "#10b981";
      ctx.lineWidth = 2;
      ctx.beginPath();
      waypoints.forEach((wp, idx) => {
        const pt = toScreen(wp.x, wp.y, wp.z);
        if (idx === 0) ctx.moveTo(pt.x, pt.y);
        else ctx.lineTo(pt.x, pt.y);
      });
      ctx.stroke();

      // Waypoint Node Rings
      waypoints.forEach((wp) => {
        const pt = toScreen(wp.x, wp.y, wp.z);
        ctx.fillStyle = "#10b981";
        ctx.beginPath();
        ctx.arc(pt.x, pt.y, 3.5, 0, Math.PI * 2);
        ctx.fill();
      });
    }

    // 4. Render Spot Ground Carrier Base Station (Parked at X=13.0, Y=0, Z=1.35)
    const spotPos = toScreen(13.0, 0, 1.35);
    ctx.fillStyle = "#f59e0b";
    ctx.beginPath();
    ctx.arc(spotPos.x, spotPos.y, 7, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "#fef08a";
    ctx.lineWidth = 1.5;
    ctx.stroke();

    ctx.fillStyle = "#fde047";
    ctx.font = "bold 9px monospace";
    ctx.fillText("Spot Base Station", spotPos.x + 9, spotPos.y + 3);

    // 5. Render Active Flying Drone (at current robotState.position)
    const dronePos = toScreen(
      robotState.position.x,
      robotState.position.y,
      robotState.position.z
    );

    // WiFi Link Ray connecting Flying Drone to Ground Spot Base Station!
    if (robotState.mode === "FLYING") {
      ctx.strokeStyle = "rgba(56, 189, 248, 0.75)";
      ctx.lineWidth = 1.5;
      ctx.setLineDash([3, 3]);
      ctx.beginPath();
      ctx.moveTo(dronePos.x, dronePos.y);
      ctx.lineTo(spotPos.x, spotPos.y);
      ctx.stroke();
      ctx.setLineDash([]);
    }

    // Drone Marker
    ctx.fillStyle = "#38bdf8";
    ctx.beginPath();
    ctx.arc(dronePos.x, dronePos.y, 8, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "#ffffff";
    ctx.lineWidth = 2;
    ctx.stroke();

    // Pulse Ring around Drone
    ctx.strokeStyle = "rgba(56, 189, 248, 0.6)";
    ctx.beginPath();
    ctx.arc(dronePos.x, dronePos.y, 13, 0, Math.PI * 2);
    ctx.stroke();

    ctx.fillStyle = "#38bdf8";
    ctx.font = "bold 10px monospace";
    ctx.fillText(
      robotState.mode === "FLYING" ? "VTOL Drone (Flying)" : "Rover Active",
      dronePos.x + 12,
      dronePos.y - 4
    );
  }, [
    robotState,
    sensorData,
    mapViewMode,
    showLidarLayer,
    showSonarLayer,
    showWifiLayer,
    showWaypointsLayer,
    mapZoom,
  ]);

  return (
    <div className="w-full bg-slate-900 border border-slate-800 rounded-xl p-4 shadow-xl flex flex-col gap-4 text-slate-200">
      <div className="flex items-center justify-between border-b border-slate-800 pb-2">
        <h3 className="font-semibold text-sm font-mono flex items-center gap-2 text-sky-400">
          <Activity className="w-4 h-4 text-sky-400" />
          Autonomous Multi-Sensor Perception & Power Suite
        </h3>
        <span className="text-xs font-mono text-emerald-400 bg-emerald-950/60 border border-emerald-800 px-2 py-0.5 rounded">
          ROS 2 Node: /sensor_fusion_slam (30Hz)
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Sensor 1: Visual RGB Camera Feed */}
        <div className="bg-slate-950 rounded-lg p-2.5 border border-slate-800 flex flex-col justify-between gap-2">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span className="flex items-center gap-1.5 text-sky-300 font-semibold">
              <Camera className="w-3.5 h-3.5 text-sky-400" /> RGB Camera Feed
            </span>
            {isRecording ? (
              <span className="text-[10px] px-2 py-0.5 rounded bg-rose-500/20 text-rose-400 border border-rose-500/40 font-mono font-bold flex items-center gap-1 animate-pulse">
                <Circle className="w-2 h-2 fill-rose-500 text-rose-500" /> REC {formatRecordTime(recordSeconds)}
              </span>
            ) : (
              <span className="text-slate-500 text-[10px]">Topic: /camera/image_raw</span>
            )}
          </div>

          <div className="relative w-full aspect-video rounded overflow-hidden border border-slate-800 bg-black">
            <canvas ref={cameraCanvasRef} width={320} height={180} className="w-full h-full object-cover" />
            <div className="absolute top-2 left-2 flex flex-wrap items-center gap-1">
              <span className="bg-slate-900/80 backdrop-blur text-sky-300 border border-slate-700 text-[9px] px-1.5 py-0.5 rounded font-mono font-bold">
                FPV ISO: 3200
              </span>
              <span className="bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 text-[9px] px-1.5 py-0.5 rounded font-mono font-bold">
                +{brightnessLevel === "ultra" ? "3.0" : brightnessLevel === "high" ? "1.5" : "0.0"} EV
              </span>
            </div>
            <div className="absolute top-2 right-2 flex items-center gap-1 bg-sky-950/80 backdrop-blur text-sky-300 border border-sky-500/40 text-[9px] px-1.5 py-0.5 rounded font-mono font-bold">
              <Wifi className="w-3 h-3 text-sky-400 animate-pulse" />
              <span>WiFi Stream: {sensorData.wifiBitrateMbps.toFixed(1)} Mbps</span>
            </div>
            {robotState.headlightOn && (
              <span className="absolute bottom-2 right-2 bg-amber-500/20 text-amber-300 border border-amber-500/40 text-[9px] px-1.5 py-0.5 rounded font-mono font-bold">
                LIGHT ON
              </span>
            )}
          </div>

          {/* FPV Controls: Video Record Button & Brightness Boost */}
          <div className="flex items-center gap-1.5 pt-1 border-t border-slate-800/80 font-mono text-[10px]">
            {/* Record Video Button */}
            <button
              id="btn-record-video-dash"
              onClick={() => setIsRecording(!isRecording)}
              className={`flex-1 py-1 px-2 rounded font-bold transition flex items-center justify-center gap-1.5 ${
                isRecording
                  ? "bg-rose-600 hover:bg-rose-500 text-white shadow-[0_0_10px_rgba(239,68,68,0.5)] animate-pulse"
                  : "bg-slate-900 hover:bg-slate-800 text-rose-400 border border-rose-500/30 hover:border-rose-500"
              }`}
              title={isRecording ? "Stop Video Recording" : "Start Video Recording"}
            >
              <Video className="w-3.5 h-3.5" />
              {isRecording ? `REC (${formatRecordTime(recordSeconds)})` : "Record Video"}
            </button>

            {/* Brightness Boost Toggle */}
            <button
              id="btn-toggle-camera-brightness"
              onClick={() =>
                setBrightnessLevel((prev) =>
                  prev === "standard" ? "high" : prev === "high" ? "ultra" : "standard"
                )
              }
              className="py-1 px-2 rounded bg-slate-900 hover:bg-slate-800 text-amber-300 border border-slate-700 font-bold transition flex items-center gap-1"
              title="Boost FPV Camera Brightness / Exposure"
            >
              <Sun className="w-3.5 h-3.5 text-amber-400" />
              <span className="uppercase text-[9px]">{brightnessLevel}</span>
            </button>
          </div>
        </div>

        {/* Sensor 2: 2D/3D LiDAR Occupancy Grid */}
        <div className="bg-slate-950 rounded-lg p-2.5 border border-slate-800 flex flex-col gap-2">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span className="flex items-center gap-1.5 text-emerald-300 font-semibold">
              <Scan className="w-3.5 h-3.5 text-emerald-400" /> 360° LiDAR Scan Map
            </span>
            <span className="text-slate-500">Topic: /scan (20Hz)</span>
          </div>

          <div className="relative w-full aspect-video rounded overflow-hidden border border-slate-800 bg-slate-950 flex items-center justify-center">
            <canvas ref={lidarCanvasRef} width={320} height={180} className="w-full h-full object-contain" />
          </div>
        </div>

        {/* Sensor 3: Underwater Sonar Acoustic Bathymetry */}
        <div className="bg-slate-950 rounded-lg p-2.5 border border-slate-800 flex flex-col justify-between gap-2">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span className="flex items-center gap-1.5 text-rose-300 font-semibold">
              <Waves className="w-3.5 h-3.5 text-rose-400" /> Underwater Sonar Depth
            </span>
            <span className="text-slate-500 text-[10px]">Topic: /sonar/echo</span>
          </div>

          <div className="w-full aspect-video rounded border border-slate-800 bg-slate-950 p-2.5 flex flex-col justify-between font-mono text-xs">
            <div className="flex items-center justify-between">
              <span className="text-slate-400 text-[11px]">Submerged Floor Depth:</span>
              <strong className="text-rose-400 text-xs">{sensorData.sonarDepth.toFixed(2)} meters</strong>
            </div>

            {/* Echo Signal Bar */}
            <div className="flex flex-col gap-1">
              <div className="flex justify-between text-[10px] text-slate-500">
                <span>Acoustic Echo Strength</span>
                <span>{sensorData.sonarEchoStrength.toFixed(0)} dB</span>
              </div>
              <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                <div
                  className="bg-gradient-to-r from-rose-500 to-amber-400 h-full transition-all duration-300"
                  style={{ width: `${sensorData.sonarEchoStrength}%` }}
                />
              </div>
            </div>

            <div className="flex items-center justify-between text-[10px] text-slate-400 pt-1 border-t border-slate-800/80">
              <span>Waterline Surface: <strong className="text-cyan-400">z = 0.0m</strong></span>
              <span>Sonar Status: <strong className={sensorData.sonarActive ? "text-emerald-400" : "text-slate-500"}>{sensorData.sonarActive ? "ACTIVE (PINGING)" : "OFF"}</strong></span>
            </div>
          </div>

          {/* Underwater Sonar Interactive Button */}
          <div className="pt-1 border-t border-slate-800/80 font-mono text-[10px]">
            <button
              id="btn-toggle-sonar-dashboard"
              onClick={onToggleSonar}
              className={`w-full py-1 px-2 rounded font-bold transition flex items-center justify-center gap-1.5 ${
                sensorData.sonarActive
                  ? "bg-rose-600 hover:bg-rose-500 text-white shadow-[0_0_10px_rgba(244,63,94,0.4)]"
                  : "bg-slate-900 hover:bg-slate-800 text-rose-300 border border-rose-500/30"
              }`}
              title="Toggle Underwater Bathymetric Acoustic Sonar Pulse"
            >
              <Radio className="w-3.5 h-3.5 text-rose-300 animate-pulse" />
              {sensorData.sonarActive ? "Disable Underwater Sonar" : "Enable Underwater Sonar"}
            </button>
          </div>
        </div>

        {/* Sensor 4 / BMS: Visual Battery Health & Power Monitor */}
        <div
          className={`bg-slate-950 rounded-lg p-2.5 border transition-all flex flex-col justify-between gap-2 font-mono text-xs ${
            isLowBattery
              ? "border-rose-500/80 bg-rose-950/20 shadow-[0_0_15px_rgba(244,63,94,0.25)]"
              : "border-slate-800"
          }`}
        >
          <div className="flex items-center justify-between text-xs font-mono">
            <span
              className={`flex items-center gap-1.5 font-semibold ${
                isLowBattery ? "text-rose-400" : "text-emerald-300"
              }`}
            >
              {isLowBattery ? (
                <BatteryWarning className="w-4 h-4 text-rose-500 animate-bounce" />
              ) : (
                <BatteryCharging className="w-4 h-4 text-emerald-400" />
              )}
              BMS Battery Health
            </span>
            <span
              className={`text-[10px] px-1.5 py-0.5 rounded border font-bold uppercase ${
                isLowBattery
                  ? "bg-rose-500/20 text-rose-300 border-rose-500/40 animate-pulse"
                  : "bg-emerald-950/80 text-emerald-400 border-emerald-800"
              }`}
            >
              {isLowBattery ? "CRITICAL LOW" : "NORMAL"}
            </span>
          </div>

          <div className="flex flex-col gap-1.5 my-0.5">
            <div className="flex items-baseline justify-between">
              <span className="text-slate-400 text-[11px]">Dynamic Charge Level:</span>
              <strong
                className={`text-base font-mono font-bold ${
                  isLowBattery
                    ? "text-rose-400"
                    : robotState.battery < 50
                    ? "text-amber-400"
                    : "text-emerald-400"
                }`}
              >
                {robotState.battery.toFixed(1)}%
              </strong>
            </div>

            {/* Visual Battery Health Progress Bar */}
            <div className="relative w-full bg-slate-900 h-3 rounded-full overflow-hidden border border-slate-800 p-0.5">
              <div
                className={`h-full rounded-full transition-all duration-300 ${
                  isLowBattery
                    ? "bg-gradient-to-r from-red-600 via-rose-500 to-red-500 animate-pulse shadow-[0_0_10px_rgba(244,63,94,0.8)]"
                    : robotState.battery < 50
                    ? "bg-gradient-to-r from-amber-500 to-yellow-400"
                    : "bg-gradient-to-r from-emerald-500 via-teal-400 to-emerald-400"
                }`}
                style={{ width: `${Math.max(0, Math.min(100, robotState.battery))}%` }}
              />
            </div>

            {/* Warning Banner when < 20% */}
            {isLowBattery && (
              <div className="p-1.5 rounded bg-rose-500/10 border border-rose-500/30 text-rose-300 text-[10px] flex items-center gap-1.5 font-sans animate-pulse">
                <AlertTriangle className="w-3.5 h-3.5 shrink-0 text-rose-400" />
                <span>
                  <strong>LOW BATTERY WARNING:</strong> Battery &lt; 20%! Triggering RTL protocol.
                </span>
              </div>
            )}
          </div>

          {/* BMS Power Specs */}
          <div className="grid grid-cols-2 gap-1 text-[10px] pt-1 border-t border-slate-800/80 text-slate-400">
            <div>
              Bus: <strong className="text-slate-200">{(22.2 * (robotState.battery / 100)).toFixed(1)}V</strong>
            </div>
            <div>
              Draw:{" "}
              <strong className="text-slate-200">
                {robotState.mode === "FLYING"
                  ? "38.2A"
                  : robotState.mode === "SAILING"
                  ? "8.4A"
                  : "12.1A"}
              </strong>
            </div>
          </div>

          {/* Quick Test Actions */}
          {onSetBattery && (
            <div className="flex items-center gap-1.5 pt-1 border-t border-slate-800/60">
              <button
                id="btn-test-low-battery"
                onClick={() => onSetBattery(15)}
                className="flex-1 py-1 rounded bg-rose-950/60 hover:bg-rose-900/80 text-rose-300 border border-rose-800/60 text-[10px] font-bold transition flex items-center justify-center gap-1"
                title="Simulate low battery (<20%)"
              >
                <Zap className="w-3 h-3 text-rose-400" /> Test 15%
              </button>
              <button
                id="btn-recharge-battery"
                onClick={() => onSetBattery(100)}
                className="flex-1 py-1 rounded bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-700 text-[10px] font-medium transition flex items-center justify-center gap-1"
              >
                <RefreshCw className="w-3 h-3 text-emerald-400" /> Charge 100%
              </button>
            </div>
          )}
        </div>
      </div>

      {/* ========================================================================= */}
      {/* BOTTOM SLAM MAPPING RESULT WINDOW */}
      {/* ========================================================================= */}
      <div className="bg-slate-950 rounded-xl p-3.5 border border-slate-800 flex flex-col gap-3 font-mono">
        {/* Header Bar */}
        <div className="flex flex-wrap items-center justify-between gap-2 pb-2 border-b border-slate-800">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-sky-500/10 text-sky-400 border border-sky-500/30">
              <Map className="w-4 h-4 text-sky-400" />
            </span>
            <div>
              <h4 className="text-xs font-bold text-sky-300 uppercase tracking-wider flex items-center gap-1.5">
                3D SLAM Mapping & Reconstruction Result Window
                <Sparkles className="w-3.5 h-3.5 text-amber-400" />
              </h4>
              <p className="text-[10px] text-slate-400">
                Real-time multi-modal point cloud aggregation & bathymetric surface profile
              </p>
            </div>
          </div>

          {/* View Mode Controls & Projection Toggles */}
          <div className="flex flex-wrap items-center gap-1.5 bg-slate-900 p-1 rounded-lg border border-slate-800 text-[11px]">
            <span className="text-slate-400 text-[10px] px-1 font-semibold">View:</span>
            <button
              id="btn-map-view-iso"
              onClick={() => setMapViewMode("iso")}
              className={`px-2 py-0.5 rounded transition ${
                mapViewMode === "iso"
                  ? "bg-sky-600 text-white font-bold shadow"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              Isometric 3D
            </button>
            <button
              id="btn-map-view-topdown"
              onClick={() => setMapViewMode("topdown")}
              className={`px-2 py-0.5 rounded transition ${
                mapViewMode === "topdown"
                  ? "bg-sky-600 text-white font-bold shadow"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              2D Occupancy
            </button>
            <button
              id="btn-map-view-side"
              onClick={() => setMapViewMode("side")}
              className={`px-2 py-0.5 rounded transition ${
                mapViewMode === "side"
                  ? "bg-sky-600 text-white font-bold shadow"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              Side Elevation
            </button>
          </div>
        </div>

        {/* Map Canvas with Floating Layer Control Toggles */}
        <div className="relative w-full aspect-[21/8] min-h-[220px] rounded-lg overflow-hidden border border-slate-800 bg-slate-950">
          <canvas
            ref={mapCanvasRef}
            width={960}
            height={320}
            className="w-full h-full object-cover"
          />

          {/* Layer Filter Buttons Overlay */}
          <div className="absolute top-2 left-2 flex flex-wrap items-center gap-1 bg-slate-900/80 backdrop-blur-md p-1 rounded-md border border-slate-700/80 text-[10px]">
            <button
              onClick={() => setShowLidarLayer(!showLidarLayer)}
              className={`px-2 py-0.5 rounded transition flex items-center gap-1 ${
                showLidarLayer
                  ? "bg-amber-500/20 text-amber-300 border border-amber-500/50 font-bold"
                  : "text-slate-500 line-through"
              }`}
            >
              <Box className="w-3 h-3 text-amber-400" />
              3D LiDAR
            </button>
            <button
              onClick={() => setShowSonarLayer(!showSonarLayer)}
              className={`px-2 py-0.5 rounded transition flex items-center gap-1 ${
                showSonarLayer
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/50 font-bold"
                  : "text-slate-500 line-through"
              }`}
            >
              <Waves className="w-3 h-3 text-cyan-400" />
              Sonar Seabed
            </button>
            <button
              onClick={() => setShowWifiLayer(!showWifiLayer)}
              className={`px-2 py-0.5 rounded transition flex items-center gap-1 ${
                showWifiLayer
                  ? "bg-lime-500/20 text-lime-300 border border-lime-500/50 font-bold"
                  : "text-slate-500 line-through"
              }`}
            >
              <Wifi className="w-3 h-3 text-lime-400" />
              WiFi Keyframes
            </button>
            <button
              onClick={() => setShowWaypointsLayer(!showWaypointsLayer)}
              className={`px-2 py-0.5 rounded transition flex items-center gap-1 ${
                showWaypointsLayer
                  ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/50 font-bold"
                  : "text-slate-500 line-through"
              }`}
            >
              <Compass className="w-3 h-3 text-emerald-400" />
              Trajectory
            </button>
          </div>

          {/* Zoom Controls Overlay */}
          <div className="absolute bottom-2 right-2 flex items-center gap-1 bg-slate-900/80 backdrop-blur p-1 rounded border border-slate-700 text-[10px]">
            <button
              onClick={() => setMapZoom((z) => Math.max(0.6, z - 0.2))}
              className="px-2 py-0.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold"
              title="Zoom Out Map"
            >
              -
            </button>
            <span className="px-1 text-sky-300 font-mono font-bold">
              {(mapZoom * 100).toFixed(0)}%
            </span>
            <button
              onClick={() => setMapZoom((z) => Math.min(2.5, z + 0.2))}
              className="px-2 py-0.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold"
              title="Zoom In Map"
            >
              +
            </button>
          </div>
        </div>

        {/* SLAM Metrics & Export Action Bar */}
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2 text-[10px] pt-1">
          <div className="bg-slate-900/80 p-2 rounded border border-slate-800 flex flex-col gap-0.5">
            <span className="text-slate-400">Mapped Volume:</span>
            <strong className="text-emerald-400 text-xs font-bold">1,845.2 m³</strong>
          </div>
          <div className="bg-slate-900/80 p-2 rounded border border-slate-800 flex flex-col gap-0.5">
            <span className="text-slate-400">PCD Point Count:</span>
            <strong className="text-sky-400 text-xs font-bold">142,850 pts</strong>
          </div>
          <div className="bg-slate-900/80 p-2 rounded border border-slate-800 flex flex-col gap-0.5">
            <span className="text-slate-400">Map Resolution:</span>
            <strong className="text-amber-300 text-xs font-bold">0.05 m (5 cm)</strong>
          </div>
          <div className="bg-slate-900/80 p-2 rounded border border-slate-800 flex flex-col gap-0.5">
            <span className="text-slate-400">Loop Closures:</span>
            <strong className="text-purple-300 text-xs font-bold">14 Closures</strong>
          </div>
          <div className="bg-slate-900/80 p-2 rounded border border-slate-800 flex flex-col gap-0.5">
            <span className="text-slate-400">Shaft Chimney:</span>
            <strong className="text-sky-300 text-xs font-bold">25.0m Mapped</strong>
          </div>

          {/* Export Map Action Button */}
          <div className="flex items-center">
            <button
              id="btn-export-pcd-map"
              onClick={handleExportPcdMap}
              disabled={isExportingMap}
              className="w-full h-full min-h-[34px] py-1 px-2.5 rounded bg-sky-600 hover:bg-sky-500 text-white font-bold transition flex items-center justify-center gap-1.5 border border-sky-400/40 shadow-lg"
            >
              {isExportingMap ? (
                <RefreshCw className="w-3.5 h-3.5 animate-spin text-white" />
              ) : (
                <Download className="w-3.5 h-3.5 text-white" />
              )}
              <span>{isExportingMap ? "Generating..." : "Export PCD Map"}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

