import React, { useState, useEffect, useRef } from "react";
import { RobotState, SensorData } from "../types";
import {
  Waves,
  Camera,
  Cpu,
  Activity,
  Sparkles,
  BarChart3,
  Sliders,
  Layers,
  Download,
  Play,
  Pause,
  RotateCcw,
  ShieldAlert,
  Zap,
  Maximize2,
  CheckCircle2,
  Target,
  Search,
  Radio,
  FileSpreadsheet,
} from "lucide-react";

// Image import paths generated by Gemini
import sicSlamArchImg from "../assets/images/sic_slam_architecture_1785597195381.jpg";
import sicSlamBenchImg from "../assets/images/sic_slam_benchmark_1785597210247.jpg";
import subseaBathymetryImg from "../assets/images/subsea_bathymetry_reconstruction_1785597224433.jpg";

interface SICSlamVisualizerProps {
  robotState: RobotState;
  sensorData: SensorData;
}

export const SICSlamVisualizer: React.FC<SICSlamVisualizerProps> = ({
  robotState,
  sensorData,
}) => {
  // State for interactive simulation
  const [isSimulating, setIsSimulating] = useState(true);
  const [activeTab, setActiveTab] = useState<"overview" | "illustrations" | "benchmark" | "factorgraph">("overview");
  const [selectedIllustration, setSelectedIllustration] = useState<"arch" | "bench" | "bathymetry">("arch");

  // Sensor Weights & Algorithm Config
  const [sonarWeight, setSonarWeight] = useState<number>(0.85);
  const [cameraWeight, setCameraWeight] = useState<number>(0.65);
  const [imuInEKFBias, setImuInEKFBias] = useState<number>(0.02);
  const [hydrostaticPrior, setHydrostaticPrior] = useState<boolean>(true);
  const [turbidityLevel, setTurbidityLevel] = useState<"Low" | "Medium" | "High" | "Severe">("Medium");

  // Metrics tracking
  const [ateSICSlam, setAteSICSlam] = useState<number>(0.042);
  const [ateVIO, setAteVIO] = useState<number>(0.385);
  const [ateDeadReckoning, setAteDeadReckoning] = useState<number>(1.842);
  const [loopClosureCount, setLoopClosureCount] = useState<number>(18);
  const [acousticFeatures, setAcousticFeatures] = useState<number>(142);

  // Canvases
  const sonarCanvasRef = useRef<HTMLCanvasElement>(null);
  const factorGraphCanvasRef = useRef<HTMLCanvasElement>(null);

  // Real-time loop update for canvas animation
  useEffect(() => {
    if (!isSimulating) return;

    const interval = setInterval(() => {
      // Simulate live jitter and EKF convergence updates
      setAteSICSlam(+(0.038 + Math.sin(Date.now() * 0.002) * 0.006).toFixed(3));
      setAteVIO(+(0.370 + Math.sin(Date.now() * 0.003) * 0.025).toFixed(3));
      setAteDeadReckoning((prev) => +(prev + 0.001).toFixed(3));
      setAcousticFeatures(130 + Math.floor(Math.random() * 25));
    }, 400);

    return () => clearInterval(interval);
  }, [isSimulating]);

  // Render Acoustic Multibeam Sonar Polar Canvas (120 degree fan beam sweep)
  useEffect(() => {
    const canvas = sonarCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = canvas.width;
    const h = canvas.height;
    const cx = w / 2;
    const cy = h - 20;
    const radius = Math.min(w / 2 - 20, h - 40);

    ctx.fillStyle = "#020617";
    ctx.fillRect(0, 0, w, h);

    // Draw polar grid rings
    ctx.strokeStyle = "rgba(6, 182, 212, 0.25)";
    ctx.lineWidth = 1;
    for (let r = radius / 4; r <= radius; r += radius / 4) {
      ctx.beginPath();
      ctx.arc(cx, cy, r, -Math.PI * 0.85, -Math.PI * 0.15);
      ctx.stroke();

      // Range text labels
      ctx.fillStyle = "#06b6d4";
      ctx.font = "9px monospace";
      ctx.fillText(`${((r / radius) * 15).toFixed(1)}m`, cx + 4, cy - r + 3);
    }

    // Draw fan sector bounding lines (120 degrees total FOV)
    ctx.strokeStyle = "rgba(6, 182, 212, 0.5)";
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.lineTo(cx + radius * Math.cos(-Math.PI * 0.833), cy + radius * Math.sin(-Math.PI * 0.833));
    ctx.moveTo(cx, cy);
    ctx.lineTo(cx + radius * Math.cos(-Math.PI * 0.167), cy + radius * Math.sin(-Math.PI * 0.167));
    ctx.stroke();

    // Sweeping sonar beam line
    const sweepAngle = -Math.PI * 0.833 + ((Date.now() * 0.002) % (Math.PI * 0.666));
    ctx.strokeStyle = "rgba(52, 211, 153, 0.8)";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.lineTo(cx + radius * Math.cos(sweepAngle), cy + radius * Math.sin(sweepAngle));
    ctx.stroke();

    // Simulated Acoustic Echo Highlights (Cave wall contours)
    ctx.fillStyle = "#10b981";
    for (let i = 0; i < 45; i++) {
      const angle = -Math.PI * 0.8 + (i / 45) * (Math.PI * 0.6);
      const baseDist = radius * 0.65 + Math.sin(i * 0.3) * radius * 0.15;
      const noise = (Math.random() - 0.5) * 6;
      const px = cx + (baseDist + noise) * Math.cos(angle);
      const py = cy + (baseDist + noise) * Math.sin(angle);

      const intensity = Math.min(1, 0.4 + Math.random() * 0.6);
      ctx.fillStyle = `rgba(52, 211, 153, ${intensity})`;
      ctx.beginPath();
      ctx.arc(px, py, 2 + intensity * 2, 0, Math.PI * 2);
      ctx.fill();
    }

    // Title label
    ctx.fillStyle = "#38bdf8";
    ctx.font = "bold 10px monospace";
    ctx.fillText("FLS ACOUSTIC MULTIBEAM FAN (1.2MHz)", 10, 16);
    ctx.fillStyle = "#10b981";
    ctx.fillText(`Acoustic Features: ${acousticFeatures}`, w - 150, 16);
  }, [acousticFeatures]);

  // Render Factor Graph Canvas (Pose nodes, Sonar factors, Camera factors, Depth prior factors)
  useEffect(() => {
    const canvas = factorGraphCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = canvas.width;
    const h = canvas.height;

    ctx.fillStyle = "#020617";
    ctx.fillRect(0, 0, w, h);

    // Draw background grid
    ctx.strokeStyle = "rgba(30, 41, 59, 0.6)";
    ctx.lineWidth = 1;
    for (let x = 0; x < w; x += 30) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, h);
      ctx.stroke();
    }
    for (let y = 0; y < h; y += 30) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(w, y);
      ctx.stroke();
    }

    // Nodes along trajectory
    const nodeCount = 12;
    const nodes: { x: number; y: number; id: number }[] = [];
    for (let i = 0; i < nodeCount; i++) {
      const nx = 40 + i * (w - 80) / (nodeCount - 1);
      const ny = h / 2 + Math.sin(i * 0.6 + Date.now() * 0.001) * 35;
      nodes.push({ x: nx, y: ny, id: i });
    }

    // Draw edges (InEKF IMU Preintegration - Green lines)
    ctx.strokeStyle = "#10b981";
    ctx.lineWidth = 2;
    ctx.beginPath();
    nodes.forEach((n, idx) => {
      if (idx === 0) ctx.moveTo(n.x, n.y);
      else ctx.lineTo(n.x, n.y);
    });
    ctx.stroke();

    // Draw Loop Closure Factor Edge (Purple curve from node 2 to node 10)
    if (nodes.length > 10) {
      ctx.strokeStyle = "#a855f7";
      ctx.lineWidth = 2.5;
      ctx.setLineDash([4, 3]);
      ctx.beginPath();
      ctx.moveTo(nodes[2].x, nodes[2].y);
      ctx.quadraticCurveTo((nodes[2].x + nodes[10].x) / 2, h * 0.1, nodes[10].x, nodes[10].y);
      ctx.stroke();
      ctx.setLineDash([]);
    }

    // Draw Sonar / Camera Feature Landmarks (Cyan & Amber triangles)
    const landmarks = [
      { x: w * 0.3, y: h * 0.2, type: "sonar" },
      { x: w * 0.55, y: h * 0.8, type: "camera" },
      { x: w * 0.75, y: h * 0.25, type: "sonar" },
    ];

    landmarks.forEach((lm) => {
      ctx.fillStyle = lm.type === "sonar" ? "#06b6d4" : "#f59e0b";
      ctx.beginPath();
      ctx.arc(lm.x, lm.y, 5, 0, Math.PI * 2);
      ctx.fill();

      // Connect to adjacent pose nodes
      nodes.forEach((n) => {
        const dist = Math.hypot(n.x - lm.x, n.y - lm.y);
        if (dist < 110) {
          ctx.strokeStyle = lm.type === "sonar" ? "rgba(6, 182, 212, 0.35)" : "rgba(245, 158, 11, 0.35)";
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(n.x, n.y);
          ctx.lineTo(lm.x, lm.y);
          ctx.stroke();
        }
      });
    });

    // Draw Pose Nodes with Covariance Ellipses
    nodes.forEach((n, idx) => {
      // Covariance Ellipse
      ctx.strokeStyle = "rgba(56, 189, 248, 0.5)";
      ctx.fillStyle = "rgba(56, 189, 248, 0.1)";
      ctx.beginPath();
      ctx.ellipse(n.x, n.y, 8 + idx * 0.5, 5 + idx * 0.3, 0.2, 0, Math.PI * 2);
      ctx.fill();
      ctx.stroke();

      // Core Node
      ctx.fillStyle = idx === nodes.length - 1 ? "#38bdf8" : "#e2e8f0";
      ctx.beginPath();
      ctx.arc(n.x, n.y, idx === nodes.length - 1 ? 6 : 4, 0, Math.PI * 2);
      ctx.fill();

      // Node label
      ctx.fillStyle = "#94a3b8";
      ctx.font = "8px monospace";
      ctx.fillText(`X${idx}`, n.x - 6, n.y + 15);
    });

    // Header Legend
    ctx.fillStyle = "#38bdf8";
    ctx.font = "bold 10px monospace";
    ctx.fillText("SLIDING WINDOW FACTOR GRAPH OPTIMIZATION (GTSAM / Ceres)", 10, 16);
  }, [isSimulating]);

  return (
    <div className="w-full bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-2xl flex flex-col gap-5 text-slate-200 font-mono">
      {/* Top Title Banner */}
      <div className="flex flex-wrap items-center justify-between border-b border-slate-800 pb-4 gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-gradient-to-br from-cyan-500/20 to-emerald-500/20 rounded-xl border border-cyan-500/40 text-cyan-400 shadow-[0_0_15px_rgba(6,182,212,0.25)]">
            <Radio className="w-6 h-6 text-cyan-400 animate-pulse" />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-100 flex items-center gap-2">
              SIC-SLAM: Subsea Sonar-Inertial-Camera Constrained SLAM
              <span className="text-[10px] bg-cyan-950 text-cyan-300 border border-cyan-700 px-2.5 py-0.5 rounded-full font-bold">
                Invariant-EKF Factor Graph
              </span>
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Robust multi-modal sensor fusion for zero-visibility turbid water, flooded shafts & deep cave exploration
            </p>
          </div>
        </div>

        {/* Top Control Bar */}
        <div className="flex flex-wrap items-center gap-2 text-xs">
          <button
            onClick={() => setIsSimulating(!isSimulating)}
            className={`px-3 py-1.5 rounded-lg border font-bold flex items-center gap-1.5 transition shadow ${
              isSimulating
                ? "bg-amber-500/20 text-amber-300 border-amber-500/40 hover:bg-amber-500/30"
                : "bg-emerald-600 hover:bg-emerald-500 text-white border-emerald-400"
            }`}
          >
            {isSimulating ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
            <span>{isSimulating ? "Pause Fusion Engine" : "Resume Fusion"}</span>
          </button>

          <button
            onClick={() => {
              setLoopClosureCount((c) => c + 1);
              alert("🎯 Loop Closure Event Injected! Keyframe Factor added to GTSAM optimization queue.");
            }}
            className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white font-bold rounded-lg border border-purple-400 flex items-center gap-1.5 transition shadow"
          >
            <Zap className="w-4 h-4 text-amber-300" />
            <span>Trigger Loop Closure</span>
          </button>
        </div>
      </div>

      {/* Main Navigation Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-800 pb-2 text-xs">
        <button
          onClick={() => setActiveTab("overview")}
          className={`px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition ${
            activeTab === "overview"
              ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow-[0_0_10px_rgba(6,182,212,0.2)]"
              : "bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800"
          }`}
        >
          <Activity className="w-4 h-4 text-cyan-400" /> Sensor Fusion Overview
        </button>

        <button
          onClick={() => setActiveTab("illustrations")}
          className={`px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition ${
            activeTab === "illustrations"
              ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 shadow-[0_0_10px_rgba(52,211,153,0.2)]"
              : "bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800"
          }`}
        >
          <Sparkles className="w-4 h-4 text-emerald-400" /> Illustration Results & Architecture
        </button>

        <button
          onClick={() => setActiveTab("benchmark")}
          className={`px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition ${
            activeTab === "benchmark"
              ? "bg-amber-500/20 text-amber-300 border border-amber-500/40 shadow-[0_0_10px_rgba(245,158,11,0.2)]"
              : "bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800"
          }`}
        >
          <BarChart3 className="w-4 h-4 text-amber-400" /> Quantitative Benchmark (ATE/RPE)
        </button>

        <button
          onClick={() => setActiveTab("factorgraph")}
          className={`px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition ${
            activeTab === "factorgraph"
              ? "bg-purple-500/20 text-purple-300 border border-purple-500/40 shadow-[0_0_10px_rgba(168,85,247,0.2)]"
              : "bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800"
          }`}
        >
          <Layers className="w-4 h-4 text-purple-400" /> Factor Graph Topology
        </button>
      </div>

      {/* TAB 1: SENSOR FUSION OVERVIEW */}
      {activeTab === "overview" && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          {/* Left Column: Multibeam Sonar + FPV Camera Canvas Cards */}
          <div className="lg:col-span-2 flex flex-col gap-5">
            {/* Live Sonar & EKF Dual Monitor */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Sonar Fan Sweep Canvas */}
              <div className="bg-slate-950 rounded-xl p-3.5 border border-cyan-500/30 flex flex-col gap-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-cyan-300 flex items-center gap-1.5">
                    <Waves className="w-4 h-4 text-cyan-400" /> Multibeam Sonar Polar Stream
                  </span>
                  <span className="text-[10px] text-emerald-400 font-bold bg-emerald-950 px-2 py-0.5 rounded border border-emerald-800">
                    Active (15Hz)
                  </span>
                </div>
                <div className="w-full aspect-square rounded-lg overflow-hidden border border-slate-800 bg-black">
                  <canvas ref={sonarCanvasRef} width={340} height={280} className="w-full h-full object-cover" />
                </div>
              </div>

              {/* Factor Graph Pose Stream Canvas */}
              <div className="bg-slate-950 rounded-xl p-3.5 border border-purple-500/30 flex flex-col gap-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-purple-300 flex items-center gap-1.5">
                    <Layers className="w-4 h-4 text-purple-400" /> Sliding Window Factor Graph
                  </span>
                  <span className="text-[10px] text-purple-300 font-bold bg-purple-950 px-2 py-0.5 rounded border border-purple-800">
                    GTSAM Solver
                  </span>
                </div>
                <div className="w-full aspect-square rounded-lg overflow-hidden border border-slate-800 bg-black">
                  <canvas ref={factorGraphCanvasRef} width={340} height={280} className="w-full h-full object-cover" />
                </div>
              </div>
            </div>

            {/* SIC-SLAM Parameter Tuning Panel */}
            <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 flex flex-col gap-3">
              <h4 className="text-xs font-bold text-sky-300 flex items-center gap-2">
                <Sliders className="w-4 h-4 text-sky-400" />
                Invariant-EKF & Multi-Modal Fusion Parameter Matrix
              </h4>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div className="flex flex-col gap-1.5">
                  <div className="flex justify-between text-slate-300">
                    <span>FLS Sonar Factor Weight (W_sonar):</span>
                    <span className="text-cyan-400 font-bold">{sonarWeight.toFixed(2)}</span>
                  </div>
                  <input
                    type="range"
                    min="0.1"
                    max="1.0"
                    step="0.05"
                    value={sonarWeight}
                    onChange={(e) => setSonarWeight(+e.target.value)}
                    className="w-full accent-cyan-400 bg-slate-800 h-1.5 rounded cursor-pointer"
                  />
                </div>

                <div className="flex flex-col gap-1.5">
                  <div className="flex justify-between text-slate-300">
                    <span>Camera Feature Weight (W_cam):</span>
                    <span className="text-emerald-400 font-bold">{cameraWeight.toFixed(2)}</span>
                  </div>
                  <input
                    type="range"
                    min="0.1"
                    max="1.0"
                    step="0.05"
                    value={cameraWeight}
                    onChange={(e) => setCameraWeight(+e.target.value)}
                    className="w-full accent-emerald-400 bg-slate-800 h-1.5 rounded cursor-pointer"
                  />
                </div>

                <div className="flex flex-col gap-1.5">
                  <div className="flex justify-between text-slate-300">
                    <span>InEKF Gyro Drift Bias Threshold:</span>
                    <span className="text-amber-400 font-bold">{imuInEKFBias.toFixed(3)} rad/s</span>
                  </div>
                  <input
                    type="range"
                    min="0.001"
                    max="0.05"
                    step="0.002"
                    value={imuInEKFBias}
                    onChange={(e) => setImuInEKFBias(+e.target.value)}
                    className="w-full accent-amber-400 bg-slate-800 h-1.5 rounded cursor-pointer"
                  />
                </div>

                <div className="flex flex-col gap-1.5">
                  <span className="text-slate-300">Water Turbidity De-hazing Level:</span>
                  <div className="grid grid-cols-4 gap-1">
                    {(["Low", "Medium", "High", "Severe"] as const).map((lvl) => (
                      <button
                        key={lvl}
                        onClick={() => setTurbidityLevel(lvl)}
                        className={`py-1 rounded text-[10px] font-bold transition ${
                          turbidityLevel === lvl
                            ? "bg-sky-600 text-white border border-sky-400"
                            : "bg-slate-900 text-slate-400 border border-slate-800"
                        }`}
                      >
                        {lvl}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Live Telemetry & EKF Status Cards */}
          <div className="flex flex-col gap-4">
            <div className="bg-slate-950 rounded-xl p-4 border border-emerald-500/30 flex flex-col gap-3">
              <h4 className="text-xs font-bold text-emerald-300 uppercase tracking-wider flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" /> SIC-SLAM Estimation Health
              </h4>

              <div className="flex flex-col gap-2 text-xs">
                <div className="bg-slate-900 p-2.5 rounded border border-slate-800 flex justify-between items-center">
                  <span className="text-slate-400">ATE RMSE (SIC-SLAM):</span>
                  <strong className="text-emerald-400 text-sm font-bold">{ateSICSlam.toFixed(3)} m</strong>
                </div>

                <div className="bg-slate-900 p-2.5 rounded border border-slate-800 flex justify-between items-center">
                  <span className="text-slate-400">ATE RMSE (Pure VIO):</span>
                  <strong className="text-amber-400 text-sm font-bold">{ateVIO.toFixed(3)} m</strong>
                </div>

                <div className="bg-slate-900 p-2.5 rounded border border-slate-800 flex justify-between items-center">
                  <span className="text-slate-400">Dead Reckoning Drift:</span>
                  <strong className="text-rose-400 text-sm font-bold">{ateDeadReckoning.toFixed(3)} m</strong>
                </div>

                <div className="bg-slate-900 p-2.5 rounded border border-slate-800 flex justify-between items-center">
                  <span className="text-slate-400">Loop Closures Validated:</span>
                  <strong className="text-purple-300 text-sm font-bold">{loopClosureCount} Matches</strong>
                </div>

                <div className="bg-slate-900 p-2.5 rounded border border-slate-800 flex justify-between items-center">
                  <span className="text-slate-400">Hydrostatic Depth Prior:</span>
                  <span className="text-cyan-300 font-bold bg-cyan-950 px-2 py-0.5 rounded border border-cyan-800">
                    {Math.abs(robotState.position.z).toFixed(2)}m (Active)
                  </span>
                </div>
              </div>
            </div>

            {/* Subsea Environmental Constraints Summary */}
            <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 flex flex-col gap-3">
              <h4 className="text-xs font-bold text-sky-300 flex items-center gap-1.5">
                <ShieldAlert className="w-4 h-4 text-sky-400" /> Hydrodynamic Constraints
              </h4>

              <ul className="text-xs text-slate-300 space-y-2 list-disc pl-4">
                <li><b className="text-cyan-300">Acoustic Refraction Correction:</b> Snell-Descartes ray-tracing compensates for salinity gradients.</li>
                <li><b className="text-emerald-300">Invariant Lie Group Action:</b> SE_2(3) invariant filtering guarantees frame independence.</li>
                <li><b className="text-amber-300">Subsea Wall Contact Factor:</b> Ultrasonic seabed echo eliminates vertical drift.</li>
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: ILLUSTRATION RESULTS & ARCHITECTURE GALLERY */}
      {activeTab === "illustrations" && (
        <div className="flex flex-col gap-5">
          {/* Gallery Selector Buttons */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <button
              onClick={() => setSelectedIllustration("arch")}
              className={`p-4 rounded-xl border text-left flex flex-col gap-2 transition ${
                selectedIllustration === "arch"
                  ? "bg-slate-950 border-cyan-500 shadow-[0_0_15px_rgba(6,182,212,0.25)]"
                  : "bg-slate-950/60 border-slate-800 hover:border-slate-700"
              }`}
            >
              <div className="flex items-center justify-between text-xs font-bold">
                <span className="text-cyan-300 flex items-center gap-1.5">
                  <Cpu className="w-4 h-4 text-cyan-400" /> 1. Factor Graph Architecture
                </span>
                <span className="text-[10px] bg-cyan-950 text-cyan-400 px-2 py-0.5 rounded border border-cyan-800">
                  Diagram
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                Multi-sensor factor graph integrating sonar fan, visual keyframes, and Lie Group InEKF nodes.
              </p>
            </button>

            <button
              onClick={() => setSelectedIllustration("bench")}
              className={`p-4 rounded-xl border text-left flex flex-col gap-2 transition ${
                selectedIllustration === "bench"
                  ? "bg-slate-950 border-amber-500 shadow-[0_0_15px_rgba(245,158,11,0.25)]"
                  : "bg-slate-950/60 border-slate-800 hover:border-slate-700"
              }`}
            >
              <div className="flex items-center justify-between text-xs font-bold">
                <span className="text-amber-300 flex items-center gap-1.5">
                  <BarChart3 className="w-4 h-4 text-amber-400" /> 2. Benchmark Comparison
                </span>
                <span className="text-[10px] bg-amber-950 text-amber-400 px-2 py-0.5 rounded border border-amber-800">
                  Quantitative
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                Trajectory error (ATE RMSE) comparison across turbid subsea cave passages.
              </p>
            </button>

            <button
              onClick={() => setSelectedIllustration("bathymetry")}
              className={`p-4 rounded-xl border text-left flex flex-col gap-2 transition ${
                selectedIllustration === "bathymetry"
                  ? "bg-slate-950 border-emerald-500 shadow-[0_0_15px_rgba(52,211,153,0.25)]"
                  : "bg-slate-950/60 border-slate-800 hover:border-slate-700"
              }`}
            >
              <div className="flex items-center justify-between text-xs font-bold">
                <span className="text-emerald-300 flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-emerald-400" /> 3. Subsea 3D Bathymetry
                </span>
                <span className="text-[10px] bg-emerald-950 text-emerald-400 px-2 py-0.5 rounded border border-emerald-800">
                  Reconstruction
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                Textured 3D point cloud mesh generated by multibeam acoustic + visual keyframe alignment.
              </p>
            </button>
          </div>

          {/* High-Resolution Generated Illustration Display */}
          <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 flex flex-col gap-3 shadow-2xl">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-sky-300 flex items-center gap-2">
                <Maximize2 className="w-4 h-4 text-sky-400" />
                {selectedIllustration === "arch" && "SIC-SLAM Sonar-Inertial-Camera Factor Graph Architecture"}
                {selectedIllustration === "bench" && "Subsea Cave SLAM Benchmark & Trajectory Error Analysis"}
                {selectedIllustration === "bathymetry" && "Subsea Bathymetric Point Cloud & Mesh Reconstruction"}
              </h3>

              <div className="flex items-center gap-2 text-xs">
                <span className="text-slate-400 text-[11px]">16:9 High-Res Render</span>
                <a
                  href={
                    selectedIllustration === "arch"
                      ? sicSlamArchImg
                      : selectedIllustration === "bench"
                      ? sicSlamBenchImg
                      : subseaBathymetryImg
                  }
                  download="sic_slam_illustration.jpg"
                  className="px-3 py-1 bg-slate-800 hover:bg-slate-700 text-sky-300 rounded border border-slate-700 font-bold flex items-center gap-1 transition"
                >
                  <Download className="w-3.5 h-3.5" /> Save Image
                </a>
              </div>
            </div>

            <div className="relative w-full aspect-video rounded-xl overflow-hidden border border-slate-800 bg-black shadow-inner">
              <img
                src={
                  selectedIllustration === "arch"
                    ? sicSlamArchImg
                    : selectedIllustration === "bench"
                    ? sicSlamBenchImg
                    : subseaBathymetryImg
                }
                alt="SIC-SLAM Illustration Result"
                referrerPolicy="no-referrer"
                className="w-full h-full object-contain"
              />

              {/* Analytical Overlay Annotations */}
              <div className="absolute bottom-3 left-3 bg-slate-950/90 backdrop-blur-md p-3 rounded-lg border border-slate-700 max-w-md text-xs">
                <span className="text-emerald-400 font-bold block mb-1">
                  {selectedIllustration === "arch" && "Key Innovation: Invariant EKF Lie Group SE_2(3) State Space"}
                  {selectedIllustration === "bench" && "Experimental Result: 89% ATE Error Reduction vs Pure VIO"}
                  {selectedIllustration === "bathymetry" && "Subsea Mapping: 0.02m Voxel Resolution @ 250m Depth"}
                </span>
                <p className="text-[11px] text-slate-300 leading-relaxed">
                  {selectedIllustration === "arch" &&
                    "Integrates multibeam sonar acoustic range images with IMU preintegration and turbidity-filtered visual keyframe factors in a sliding window graph."}
                  {selectedIllustration === "bench" &&
                    "Benchmarked across flooded cave passages with zero visual visibility. Sonar factors maintain drift-free localization even during complete turbidity washouts."}
                  {selectedIllustration === "bathymetry" &&
                    "High-density point cloud aggregated from 256 acoustic sonar beams fused with ROV FPV camera keyframes for subsea geology inspection."}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: QUANTITATIVE BENCHMARK */}
      {activeTab === "benchmark" && (
        <div className="bg-slate-950 rounded-xl p-5 border border-slate-800 flex flex-col gap-4">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div>
              <h3 className="text-sm font-bold text-amber-300 flex items-center gap-2">
                <BarChart3 className="w-5 h-5 text-amber-400" />
                Quantitative Algorithm Benchmark (Subsea Cave Dataset)
              </h3>
              <p className="text-xs text-slate-400">
                Comparison of Absolute Trajectory Error (ATE RMSE), Relative Pose Error (RPE), and Drift %
              </p>
            </div>

            <button
              onClick={() => {
                const csvData = `Algorithm,ATE_RMSE_m,RPE_Trans_m,RPE_Rot_deg,Drift_Percent,Latency_ms\nSIC-SLAM,0.042,0.012,0.18,0.12%,18.4\nVisual-Inertial SLAM,0.385,0.094,1.42,1.85%,24.2\nPure Dead Reckoning,1.842,0.412,5.20,8.40%,2.1`;
                const blob = new Blob([csvData], { type: "text/csv" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = "sic_slam_benchmark_results.csv";
                a.click();
              }}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-sky-300 font-bold rounded border border-slate-700 flex items-center gap-1.5 transition text-xs"
            >
              <FileSpreadsheet className="w-4 h-4 text-emerald-400" /> Export Benchmark CSV
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-slate-400 bg-slate-900/60">
                  <th className="p-3">SLAM Algorithm</th>
                  <th className="p-3">Sensor Modalities</th>
                  <th className="p-3">ATE RMSE (m)</th>
                  <th className="p-3">RPE Translation (m)</th>
                  <th className="p-3">Drift (% Traveled)</th>
                  <th className="p-3">Mean Latency</th>
                  <th className="p-3">Turbidity Resilience</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                <tr className="bg-emerald-950/20 text-emerald-300 font-bold border-l-4 border-l-emerald-400">
                  <td className="p-3 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" /> SIC-SLAM (Proposed)
                  </td>
                  <td className="p-3 text-slate-300">Multibeam Sonar + InEKF IMU + Camera</td>
                  <td className="p-3 text-emerald-400 font-bold text-sm">{ateSICSlam.toFixed(3)} m</td>
                  <td className="p-3">0.012 m</td>
                  <td className="p-3 text-emerald-400">0.12 %</td>
                  <td className="p-3">18.4 ms</td>
                  <td className="p-3">
                    <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                      100% (Immune)
                    </span>
                  </td>
                </tr>

                <tr className="text-slate-300">
                  <td className="p-3 font-semibold">Visual-Inertial SLAM (ORB-SLAM3)</td>
                  <td className="p-3 text-slate-400">Stereo Camera + IMU</td>
                  <td className="p-3 text-amber-400 font-bold">{ateVIO.toFixed(3)} m</td>
                  <td className="p-3">0.094 m</td>
                  <td className="p-3 text-amber-400">1.85 %</td>
                  <td className="p-3">24.2 ms</td>
                  <td className="p-3">
                    <span className="px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/40">
                      35% (Fails in Silt)
                    </span>
                  </td>
                </tr>

                <tr className="text-slate-300">
                  <td className="p-3 font-semibold">Subsea Dead Reckoning</td>
                  <td className="p-3 text-slate-400">IMU + DVL (Doppler Velocity Log)</td>
                  <td className="p-3 text-rose-400 font-bold">{ateDeadReckoning.toFixed(3)} m</td>
                  <td className="p-3">0.412 m</td>
                  <td className="p-3 text-rose-400">8.40 %</td>
                  <td className="p-3">2.1 ms</td>
                  <td className="p-3">
                    <span className="px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/40">
                      Unbounded Drift
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* TAB 4: FACTOR GRAPH DETAILS */}
      {activeTab === "factorgraph" && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          <div className="bg-slate-950 rounded-xl p-4 border border-purple-500/30 flex flex-col gap-3">
            <h4 className="text-xs font-bold text-purple-300 flex items-center gap-1.5">
              <Layers className="w-4 h-4 text-purple-400" /> Factor Graph Formulation Details
            </h4>
            <div className="text-xs text-slate-300 space-y-2">
              <p>
                The total log-likelihood cost function minimized over sliding keyframes X and acoustic landmarks L is:
              </p>
              <div className="p-3 bg-black rounded border border-slate-800 font-mono text-[11px] text-cyan-300 overflow-x-auto">
                min_(X,L) [ ∑ ||r_InEKF(x_i, x_i+1)||^2 + ∑ ||r_sonar(x_i, l_j)||^2 + ∑ ||r_hydro(x_k)||^2 ]
              </div>
              <ul className="list-disc pl-4 space-y-1 text-slate-400">
                <li><b className="text-emerald-400">r_InEKF</b>: Invariant IMU preintegration error on Lie Group SE_2(3).</li>
                <li><b className="text-cyan-400">r_sonar</b>: Acoustic fan beam polar range-azimuth observation residual.</li>
                <li><b className="text-amber-400">r_hydro</b>: Hydrostatic pressure sensor depth prior constraint.</li>
              </ul>
            </div>
          </div>

          <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 flex flex-col gap-3">
            <h4 className="text-xs font-bold text-sky-300 flex items-center gap-1.5">
              <Cpu className="w-4 h-4 text-sky-400" /> ROS 2 Node Architecture
            </h4>
            <div className="p-3 bg-black rounded border border-slate-900 text-xs text-slate-300 space-y-1">
              <div><b className="text-emerald-400">Node:</b> /sic_slam_node (C++20 ROS 2 Jazzy)</div>
              <div><b className="text-cyan-400">Subscribers:</b> /sonar/range_image, /imu/data, /camera/image_raw</div>
              <div><b className="text-amber-400">Publishers:</b> /sic_slam/odometry, /sic_slam/pointcloud_3d</div>
              <div><b className="text-purple-400">GTSAM Library:</b> GTSAM v4.2 Non-linear iSAM2 Optimizer</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
